name: Sungsoo Kim's Blog
source: .
destination: ./posthtml
#markdown: redcarpet
#markdown: rdiscount
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: true
highlighter: rouge
safe: true
lsi: false
#pygments: true
highlighter: true
excerpt_separator: "\n\n"
incremental: false

domain: sungsoo.github.io
url: https://sungsoo.github.io
baseurl: ""
permalink: /:year/:month/:day/:title.html

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Sungsoo Kim's Blog
author :
  name : Sungsoo Kim
  email : sungsoo.etri@yahoo.com
  github : sungsoo

paginate: 20
comments :
    provider : disqus
    disqus :
      short_name : sungsoo
      
# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.2.13

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.com/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.com/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  # BASE_PATH : /
  BASE_PATH : https://sungsoo.github.io/

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex: 
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  ASSET_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change theme here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  
  
  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  analytics :
  provider : google
  google : 
  tracking_id : 'UA-41397016-2'

  
  setup :
    provider : 'custom'
    
    
jekyll_sort:
  - src: numbers
    direction: up
    dest: numbers_sorted
  - src: posts
    by: date
    direction: down
    dest: posts_sorted_by_date_desc
  - src: all_content
    by: sort
    direction: up
    dest: all_promoted_by_sort
    include_tags: 
    - promoted
    - news
